version: "3.7"

services:
    go_app:
        build:
            context: .
            dockerfile: Dockerfile.server
        container_name: go_server
        ports: 
            - 3000:3000
        volumes: 
            - ./server:/go/src/server
        env_file: 
            - ./server/configs.env
        depends_on: 
            - db
        networks: 
            - inner_host
    
    db:
        image: mysql:latest
        container_name: mysql_docker
        volumes:
            - book_store_mysql_data:/var/lib/mysql
        env_file: 
            - ./server/configs.env
        networks: 
            - inner_host
networks:
    inner_host:
        driver: "bridge"
volumes:
    book_store_mysql_data:            
        
        