# go_server_image
FROM golang:1.16.4-buster
ENV PATH="${PATH}:$GOPATH"
WORKDIR /go/src/server
COPY ./server .
RUN go get github.com/githubnemo/CompileDaemon
CMD go mod download
ENTRYPOINT CompileDaemon --build="go build runserver.go" --command=./runserver